use crate::win_ffi::VARTYPE;

#[allow(non_camel_case_types)]
#[derive(Debug,Default)]
#[repr(u32)]
pub enum Z7PropIDs {
    #[default]
    kpidNoProperty = 0,
    kpidMainSubfile,
    kpidHandlerItemIndex,
    kpidPath,
    kpidName,
    kpidExtension,
    kpidIsDir,
    kpidSize,
    kpidPackSize,
    kpidAttrib,
    kpidCTime,
    kpidATime,
    kpidMTime,
    kpidSolid,
    kpidCommented,
    kpidEncrypted,
    kpidSplitBefore,
    kpidSplitAfter,
    kpidDictionarySize,
    kpidCRC,
    kpidType,
    kpidIsAnti,
    kpidMethod,
    kpidHostOS,
    kpidFileSystem,
    kpidUser,
    kpidGroup,
    kpidBlock,
    kpidComment,
    kpidPosition,
    kpidPrefix,
    kpidNumSubDirs,
    kpidNumSubFiles,
    kpidUnpackVer,
    kpidVolume,
    kpidIsVolume,
    kpidOffset,
    kpidLinks,
    kpidNumBlocks,
    kpidNumVolumes,
    kpidTimeType,
    kpidBit64,
    kpidBigEndian,
    kpidCpu,
    kpidPhySize,
    kpidHeadersSize,
    kpidChecksum,
    kpidCharacts,
    kpidVa,
    kpidId,
    kpidShortName,
    kpidCreatorApp,
    kpidSectorSize,
    kpidPosixAttrib,
    kpidSymLink,
    kpidError,
    kpidTotalSize,
    kpidFreeSpace,
    kpidClusterSize,
    kpidVolumeName,
    kpidLocalName,
    kpidProvider,
    kpidNtSecure,
    kpidIsAltStream,
    kpidIsAux,
    kpidIsDeleted,
    kpidIsTree,
    kpidSha1,
    kpidSha256,
    kpidErrorType,
    kpidNumErrors,
    kpidErrorFlags,
    kpidWarningFlags,
    kpidWarning,
    kpidNumStreams,
    kpidNumAltStreams,
    kpidAltStreamsSize,
    kpidVirtualSize,
    kpidUnpackSize,
    kpidTotalPhySize,
    kpidVolumeIndex,
    kpidSubType,
    kpidShortComment,
    kpidCodePage,
    kpidIsNotArcType,
    kpidPhySizeCantBeDetected,
    kpidZerosTailIsAllowed,
    kpidTailSize,
    kpidEmbeddedStubSize,
    kpidNtReparse,
    kpidHardLink,
    kpidINode,
    kpidStreamId,
    kpidReadOnly,
    kpidOutName,
    kpidCopyLink,
    kpidArcFileName,
    kpidIsHash,
    kpidChangeTime,
    kpidUserId,
    kpidGroupId,
    kpidDeviceMajor,
    kpidDeviceMinor,
    kpidDevMajor,
    kpidDevMinor,

    kpid_NUM_DEFINED,

    kpidUserDefined = 0x10000
}

impl From<Z7PropIDs> for VARTYPE {
    fn from(value: Z7PropIDs) -> Self {
        match value {
            Z7PropIDs::kpidPath => VARTYPE::VT_BSTR,
            _ => VARTYPE::VT_ERROR //todo RM 
        } 
    }
}